/**
 * Domain configuration for Healthcare
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "healthcare",
  name: "Healthcare",
  description: "Patient care, clinical encounters, diagnoses, treatments, and provider networks",
  tagline: "AI-powered Clinical Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"Diagnosis": "#ef4444", "Encounter": "#f59e0b", "Event": "#f97316", "Facility": "#6366f1", "Location": "#a855f7", "Medication": "#8b5cf6", "Object": "#eab308", "Organization": "#3b82f6", "Patient": "#06b6d4", "Person": "#22c55e", "Provider": "#14b8a6", "Treatment": "#10b981"};

export const NODE_SIZES: Record<string, number> = {"Diagnosis": 20, "Encounter": 15, "Event": 20, "Facility": 30, "Location": 20, "Medication": 15, "Object": 20, "Organization": 20, "Patient": 25, "Person": 20, "Provider": 25, "Treatment": 15};

export const DEFAULT_CYPHER = `MATCH (p:Patient)-[r]-(n) RETURN p, r, n LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Patient Lookup", "prompts": ["Show me all patients with a chronic diagnosis", "What medications are currently prescribed to patients in the cardiology department?", "Find all recent patient encounters in the last 6 months"]}, {"name": "Clinical Decision Support", "prompts": ["Are there any potential drug interactions in current prescriptions?", "What treatments have been most effective for patients with heart failure?", "Show me the most recent decision traces for treatment plans"]}, {"name": "Provider Network", "prompts": ["Which providers are affiliated with the largest hospital in the network?", "Show the referral patterns between primary care and specialists", "Which providers have the most patient encounters this quarter?"]}];
